### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iampeterbanjo**
Fix incorrect template

### CODE REVIEW

**Comment by jongio** [comment]
@rajeshkamal5050 - Wasn't this fixed in azure-dev?

**Comment by rajeshkamal5050** [comment]
@v-xuto can you handle and fix this on the azure-dev?

**Comment by v-xuto** [comment]
> @v-xuto can you handle and fix this on the azure-dev?

@rajeshkamal5050 PR https://github.com/Azure/azure-dev/pull/2574 is ready, please review.
Besides, we also modified the readme of other templates with the same issue.

**Comment by iampeterbanjo** [comment]
Thank you all. I'll close this PR. :)

**Pull request closed without merging**
